[project]
name = "housing-dashboard"
version = "0.1.0"
description = "A Streamlit app for visualizing housing data from large CSV files."
authors = [
    { name = "Your Name", email = "your@email.com" }
]
requires-python = ">=3.8" 